"""Reports API endpoints."""

import os
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import FileResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.services.report_service import ReportService
from app.models.report import Report
from app.models.evidence import Evidence
from app.models.case import Case, CaseMember
from app.models.user import User, Role
from app.exceptions.errors import AuthorizationError, NotFoundError

router = APIRouter()


def get_user_id_from_request(request: Request) -> str:
    user_id = getattr(request.state, "user_id", None)
    if not user_id:
        raise HTTPException(status_code=401, detail="Authentication required")
    return user_id


async def _get_user_permissions(db: AsyncSession, user_id: str):
    from sqlalchemy.orm import selectinload
    result = await db.execute(
        select(User)
        .options(selectinload(User.role).selectinload(Role.permissions))
        .where(User.id == user_id)
    )
    user = result.scalar_one_or_none()
    if not user or not user.role:
        return []
    return [perm.name for perm in user.role.permissions]


@router.get("")
async def list_reports(
    request: Request,
    limit: int = 100,
    db: AsyncSession = Depends(get_db),
):
    """List all generated reports."""
    try:
        user_id = get_user_id_from_request(request)
        permissions = await _get_user_permissions(db, user_id)
        can_view_all = "AUDIT_VIEW" in permissions

        query = select(Report).order_by(Report.generated_at.desc())

        if not can_view_all:
            # Only show reports generated by this user
            query = query.where(Report.generated_by == user_id)

        query = query.limit(limit)
        result = await db.execute(query)
        reports = result.scalars().all()

        output = []
        for r in reports:
            # Get evidence external id
            evidence_ext_id = None
            if r.evidence_id:
                ev_result = await db.execute(
                    select(Evidence.evidence_id).where(Evidence.id == r.evidence_id)
                )
                evidence_ext_id = ev_result.scalar()

            # Get case number
            case_number = None
            if r.case_id:
                c_result = await db.execute(
                    select(Case.case_number).where(Case.id == r.case_id)
                )
                case_number = c_result.scalar()

            # Get generator name
            gen_result = await db.execute(
                select(User.full_name).where(User.id == r.generated_by)
            )
            generator = gen_result.scalar() or "Unknown"

            output.append({
                "report_id": r.report_id,
                "title": r.title,
                "report_type": r.report_type,
                "evidence_id": evidence_ext_id,
                "case_number": case_number,
                "generated_by": generator,
                "generated_at": r.generated_at.isoformat(),
                "status": r.status,
                "hash": r.hash,
            })

        return {"reports": output, "total": len(output)}

    except HTTPException:
        raise
    except Exception as e:
        import traceback
        print("[ERROR] list_reports:", traceback.format_exc())
        raise HTTPException(status_code=500, detail=str(e))


# ==========================================================
# CASE-LEVEL REPORT  (NEW)
# ==========================================================
@router.post("/case/{case_id}")
async def generate_case_report(
    case_id: str,
    request: Request,
    db: AsyncSession = Depends(get_db),
):
    """Generate a comprehensive case summary PDF with all evidence."""
    try:
        user_id = get_user_id_from_request(request)
        service = ReportService(db)
        result = await service.generate_case_report(user_id, case_id)
        return result
    except AuthorizationError as e:
        raise HTTPException(status_code=403, detail=e.message)
    except NotFoundError as e:
        raise HTTPException(status_code=404, detail=e.message)
    except Exception as e:
        import traceback
        print("[ERROR] generate_case_report:", traceback.format_exc())
        raise HTTPException(status_code=500, detail=str(e))


# ==========================================================
# EVIDENCE-LEVEL REPORT
# ==========================================================
@router.post("/evidence/{evidence_id}")
async def generate_evidence_report(
    evidence_id: str,
    request: Request,
    db: AsyncSession = Depends(get_db),
):
    """Generate a court-friendly PDF report for evidence."""
    try:
        user_id = get_user_id_from_request(request)
        service = ReportService(db)
        result = await service.generate_evidence_report(user_id, evidence_id)
        return result
    except AuthorizationError as e:
        raise HTTPException(status_code=403, detail=e.message)
    except NotFoundError as e:
        raise HTTPException(status_code=404, detail=e.message)
    except Exception as e:
        import traceback
        print("[ERROR] generate_evidence_report:", traceback.format_exc())
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/{report_id}/download")
async def download_report(
    report_id: str,
    request: Request,
    db: AsyncSession = Depends(get_db),
):
    """Download a generated report PDF."""
    try:
        _ = get_user_id_from_request(request)

        result = await db.execute(
            select(Report).where(Report.report_id == report_id)
        )
        report = result.scalar_one_or_none()

        if not report:
            raise HTTPException(status_code=404, detail="Report not found")

        if not os.path.exists(report.file_path):
            raise HTTPException(status_code=404, detail="Report file not found on disk")

        return FileResponse(
            report.file_path,
            media_type="application/pdf",
            filename=f"{report_id}.pdf",
        )
    except HTTPException:
        raise
    except Exception as e:
        import traceback
        print("[ERROR] download_report:", traceback.format_exc())
        raise HTTPException(status_code=500, detail=str(e))